### ISSUE TITLE
[JENKINS-37756] Broken dependency to bundled jsch-0.1.31.jar library - Ivy 2.4.0 distributes with jsch-0.1.50.jar

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/ivy-plugin#218]
<p>I use some ssh resolvers in my environment, and after upgrading ivy-plugin from version 1.24 to 1.26 I am consistently experiencing the <em>'java.lang.NoClassDefFoundError: com/jcraft/jsch/IdentityRepository'</em> as shown in the stacktrace included further below.</p>

<p>Reporters observations:</p>
<ul class="alternate" type="square">
	<li>ivy-plugin has upgraded from Ivy 2.3.0 to 2.4.0 between version 1.24 and 1.26</li>
	<li>Ivy 2.3.0 is based on (according to its ivy-xml and its '-with-dependencies' distribution bundle) jsch-0.1.31</li>
	<li>Ivy 2.4.0  is based on (according to its ivy-xml and its '-with-dependencies' distribution bundle) jsch-0.1.50</li>
	<li>The SSH repository implementation in Ivy 2.4.0 appears to depend on features (IdentityRepository and possible others) that only came into the jsch library after jsch-0.1.31.jar</li>
</ul>

<p>Reporters suggestion:</p>
<ul class="alternate" type="square">
	<li>Update the ivy-plugin to bundle the jsch-0.1.50.jar library to reflect the upgraded dependency of Ivy 2.4.0</li>
</ul>

<p>Reporters workaround:</p>
<ul class="alternate" type="square">
	<li>I manually repackaged the ivy.hpi file for ivy-plugin version 1.26 to include the jsch-0.1.50.jar library, and that appears to fully resolve the issue. However, this means running with a non-standard repository plugin. Alternatively, use ivy-plugin 1.24 (based on Ivy 2.3.0) if possible/applicable.</li>
</ul>

<p>Stacktrace from job console:<br/>
Parsing Ivy Descriptor Files<br/>
ERROR: Failed to parse ivy.xml files<br/>
java.io.IOException: Unable to parse ivy descriptors<br/>
	at hudson.ivy.IvyModuleSetBuild$RunnerImpl.parseIvyDescriptorFiles(IvyModuleSetBuild.java:545)<br/>
	at hudson.ivy.IvyModuleSetBuild$RunnerImpl.doRun(IvyModuleSetBuild.java:380)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)<br/>
	at hudson.model.Run.execute(Run.java:1738)<br/>
	at hudson.model.Run.run(Run.java:1676)<br/>
	at hudson.ivy.IvyModuleSetBuild.run(IvyModuleSetBuild.java:281)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:98)<br/>
	at hudson.model.Executor.run(Executor.java:410)<br/>
Caused by: java.lang.NoClassDefFoundError: com/jcraft/jsch/IdentityRepository<br/>
	at org.apache.ivy.plugins.repository.ssh.AbstractSshBasedRepository.getSession(AbstractSshBasedRepository.java:108)<br/>
	at org.apache.ivy.plugins.repository.ssh.SshRepository.resolveResource(SshRepository.java:82)<br/>
	at org.apache.ivy.plugins.repository.ssh.SshResource.resolve(SshResource.java:101)<br/>
	at org.apache.ivy.plugins.repository.ssh.SshResource.exists(SshResource.java:70)<br/>
	at org.apache.ivy.plugins.resolver.RepositoryResolver.findResourceUsingPattern(RepositoryResolver.java:97)<br/>
	at org.apache.ivy.plugins.resolver.AbstractPatternsBasedResolver.findResourceUsingPatterns(AbstractPatternsBasedResolver.java:97)<br/>
	at org.apache.ivy.plugins.resolver.AbstractPatternsBasedResolver.findIvyFileRef(AbstractPatternsBasedResolver.java:66)<br/>
	at org.apache.ivy.plugins.resolver.BasicResolver.getDependency(BasicResolver.java:230)<br/>
	at org.apache.ivy.plugins.resolver.ChainResolver.getDependency(ChainResolver.java:104)<br/>
	at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser$Parser.parseOtherIvyFile(XmlModuleDescriptorParser.java:725)<br/>
	at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser$Parser.extendsStarted(XmlModuleDescriptorParser.java:461)<br/>
	at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser$Parser.startElement(XmlModuleDescriptorParser.java:320)<br/>
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)<br/>
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)<br/>
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:780)<br/>
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:356)<br/>
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)<br/>
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)<br/>
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)<br/>
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)<br/>
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)<br/>
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)<br/>
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)<br/>
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)<br/>
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)<br/>
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)<br/>
	at org.apache.ivy.util.XMLHelper.parse(XMLHelper.java:162)<br/>
	at org.apache.ivy.util.XMLHelper.parse(XMLHelper.java:139)<br/>
	at org.apache.ivy.util.XMLHelper.parse(XMLHelper.java:122)<br/>
	at org.apache.ivy.util.XMLHelper.parse(XMLHelper.java:113)<br/>
	at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser$Parser.parse(XmlModuleDescriptorParser.java:268)<br/>
	at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser.parseDescriptor(XmlModuleDescriptorParser.java:119)<br/>
	at org.apache.ivy.plugins.parser.ModuleDescriptorParserRegistry.parseDescriptor(ModuleDescriptorParserRegistry.java:87)<br/>
	at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser.parseDescriptor(AbstractModuleDescriptorParser.java:48)<br/>
	at hudson.ivy.IvyModuleSetBuild$IvyXmlParser$1.doInIvyContext(IvyModuleSetBuild.java:805)<br/>
	at org.apache.ivy.Ivy.execute(Ivy.java:366)<br/>
	at hudson.ivy.IvyModuleSetBuild$IvyXmlParser.call(IvyModuleSetBuild.java:802)<br/>
	at hudson.ivy.IvyModuleSetBuild$IvyXmlParser.call(IvyModuleSetBuild.java:759)<br/>
	at hudson.FilePath.act(FilePath.java:1077)<br/>
	at hudson.ivy.IvyModuleSetBuild$RunnerImpl.parseIvyDescriptorFiles(IvyModuleSetBuild.java:539)<br/>
	... 7 more<br/>
Caused by: java.lang.ClassNotFoundException: com.jcraft.jsch.IdentityRepository<br/>
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)<br/>
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)<br/>
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)<br/>
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)<br/>
	... 47 more </p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=riksen">riksen</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-37756" target="_blank">Broken dependency to bundled jsch-0.1.31.jar library - Ivy 2.4.0 distributes with jsch-0.1.50.jar</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/tbingaman.png" title="tbingaman's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=tbingaman">tbingaman</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>component(s)</b>: ivy-plugin
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2022-11-19T21:57:49+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 20251216-225446
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>I use some ssh resolvers in my environment, and after upgrading ivy-plugin from version 1.24 to 1.26 I am consistently experiencing the <em>'java.lang.NoClassDefFoundError: com/jcraft/jsch/IdentityRepository'</em> as shown in the stacktrace included further below.</p>

<p>Reporters observations:</p>
<ul class="alternate" type="square">
	<li>ivy-plugin has upgraded from Ivy 2.3.0 to 2.4.0 between version 1.24 and 1.26</li>
	<li>Ivy 2.3.0 is based on (according to its ivy-xml and its '-with-dependencies' distribution bundle) jsch-0.1.31</li>
	<li>Ivy 2.4.0  is based on (according to its ivy-xml and its '-with-dependencies' distribution bundle) jsch-0.1.50</li>
	<li>The SSH repository implementation in Ivy 2.4.0 appears to depend on features (IdentityRepository and possible others) that only came into the jsch library after jsch-0.1.31.jar</li>
</ul>

<p>Reporters suggestion:</p>
<ul class="alternate" type="square">
	<li>Update the ivy-plugin to bundle the jsch-0.1.50.jar library to reflect the upgraded dependency of Ivy 2.4.0</li>
</ul>

<p>Reporters workaround:</p>
<ul class="alternate" type="square">
	<li>I manually repackaged the ivy.hpi file for ivy-plugin version 1.26 to include the jsch-0.1.50.jar library, and that appears to fully resolve the issue. However, this means running with a non-standard repository plugin. Alternatively, use ivy-plugin 1.24 (based on Ivy 2.3.0) if possible/applicable.</li>
</ul>

<p>Stacktrace from job console:
Parsing Ivy Descriptor Files
ERROR: Failed to parse ivy.xml files
java.io.IOException: Unable to parse ivy descriptors
	at hudson.ivy.IvyModuleSetBuild$RunnerImpl.parseIvyDescriptorFiles(IvyModuleSetBuild.java:545)
	at hudson.ivy.IvyModuleSetBuild$RunnerImpl.doRun(IvyModuleSetBuild.java:380)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.Run.run(Run.java:1676)
	at hudson.ivy.IvyModuleSetBuild.run(IvyModuleSetBuild.java:281)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: java.lang.NoClassDefFoundError: com/jcraft/jsch/IdentityRepository
	at org.apache.ivy.plugins.repository.ssh.AbstractSshBasedRepository.getSession(AbstractSshBasedRepository.java:108)
	at org.apache.ivy.plugins.repository.ssh.SshRepository.resolveResource(SshRepository.java:82)
	at org.apache.ivy.plugins.repository.ssh.SshResource.resolve(SshResource.java:101)
	at org.apache.ivy.plugins.repository.ssh.SshResource.exists(SshResource.java:70)
	at org.apache.ivy.plugins.resolver.RepositoryResolver.findResourceUsingPattern(RepositoryResolver.java:97)
	at org.apache.ivy.plugins.resolver.AbstractPatternsBasedResolver.findResourceUsingPatterns(AbstractPatternsBasedResolver.java:97)
	at org.apache.ivy.plugins.resolver.AbstractPatternsBasedResolver.findIvyFileRef(AbstractPatternsBasedResolver.java:66)
	at org.apache.ivy.plugins.resolver.BasicResolver.getDependency(BasicResolver.java:230)
	at org.apache.ivy.plugins.resolver.ChainResolver.getDependency(ChainResolver.java:104)
	at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser$Parser.parseOtherIvyFile(XmlModuleDescriptorParser.java:725)
	at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser$Parser.extendsStarted(XmlModuleDescriptorParser.java:461)
	at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser$Parser.startElement(XmlModuleDescriptorParser.java:320)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:780)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:356)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
	at org.apache.ivy.util.XMLHelper.parse(XMLHelper.java:162)
	at org.apache.ivy.util.XMLHelper.parse(XMLHelper.java:139)
	at org.apache.ivy.util.XMLHelper.parse(XMLHelper.java:122)
	at org.apache.ivy.util.XMLHelper.parse(XMLHelper.java:113)
	at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser$Parser.parse(XmlModuleDescriptorParser.java:268)
	at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser.parseDescriptor(XmlModuleDescriptorParser.java:119)
	at org.apache.ivy.plugins.parser.ModuleDescriptorParserRegistry.parseDescriptor(ModuleDescriptorParserRegistry.java:87)
	at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser.parseDescriptor(AbstractModuleDescriptorParser.java:48)
	at hudson.ivy.IvyModuleSetBuild$IvyXmlParser$1.doInIvyContext(IvyModuleSetBuild.java:805)
	at org.apache.ivy.Ivy.execute(Ivy.java:366)
	at hudson.ivy.IvyModuleSetBuild$IvyXmlParser.call(IvyModuleSetBuild.java:802)
	at hudson.ivy.IvyModuleSetBuild$IvyXmlParser.call(IvyModuleSetBuild.java:759)
	at hudson.FilePath.act(FilePath.java:1077)
	at hudson.ivy.IvyModuleSetBuild$RunnerImpl.parseIvyDescriptorFiles(IvyModuleSetBuild.java:539)
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.jcraft.jsch.IdentityRepository
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more </p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
OS: Ubuntu 14.04 LTS<br/>
Jenkins version 1.651.2<br/>
ivy-plugin version 1.26<br/>
Oracle Java version 1.8.0_60<br/>
Running Jenkins directly from war via embedded http server
```
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>basil:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-37756?focusedId=432491&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-432491">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Fixed in <a href="https://github.com/jenkinsci/ivy-plugin/pull/33" class="external-link" target="_blank" rel="nofollow noopener">jenkinsci/ivy-plugin#33</a>. Released in <a href="https://github.com/jenkinsci/ivy-plugin/releases/tag/ivy-2.0" class="external-link" target="_blank" rel="nofollow noopener">2.0</a>.</p>
</pre>
</details>

</ul>
</details>

<p>Fixed in <a href="https://github.com/jenkinsci/ivy-plugin/pull/33" class="external-link" target="_blank" rel="nofollow noopener">jenkinsci/ivy-plugin#33</a>. Released in <a href="https://github.com/jenkinsci/ivy-plugin/releases/tag/ivy-2.0" class="external-link" target="_blank" rel="nofollow noopener">2.0</a>.</p>
