### ISSUE TITLE
[JENKINS-6309] Ivy plugin does not work in Hudson 1.355

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/ivy-plugin#165]
<p>I get the following when running 1.5 on Hudson 1.355.</p>

<p>FATAL: hudson.ivy.IvyModuleSetBuild$RunnerImpl.performAllBuildStep(Lhudson/model/BuildListener;Ljava/lang/Iterable;Z)V<br/>
java.lang.NoSuchMethodError: hudson.ivy.IvyModuleSetBuild$RunnerImpl.performAllBuildStep(Lhudson/model/BuildListener;Ljava/lang/Iterable;Z)V<br/>
	at hudson.ivy.IvyModuleSetBuild$RunnerImpl.post2(IvyModuleSetBuild.java:589)<br/>
	at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:528)<br/>
	at hudson.model.Run.run(Run.java:1267)<br/>
	at hudson.ivy.IvyModuleSetBuild.run(IvyModuleSetBuild.java:283)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:122)</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=bloomper">bloomper</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-6309" target="_blank">Ivy plugin does not work in Hudson 1.355</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=hibou">hibou</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>component(s)</b>: ivy-plugin
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2010-04-20T14:38:30+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 0
<li><b>imported</b>: 20251216-225446
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>I get the following when running 1.5 on Hudson 1.355.</p>

<p>FATAL: hudson.ivy.IvyModuleSetBuild$RunnerImpl.performAllBuildStep(Lhudson/model/BuildListener;Ljava/lang/Iterable;Z)V
java.lang.NoSuchMethodError: hudson.ivy.IvyModuleSetBuild$RunnerImpl.performAllBuildStep(Lhudson/model/BuildListener;Ljava/lang/Iterable;Z)V
	at hudson.ivy.IvyModuleSetBuild$RunnerImpl.post2(IvyModuleSetBuild.java:589)
	at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:528)
	at hudson.model.Run.run(Run.java:1267)
	at hudson.ivy.IvyModuleSetBuild.run(IvyModuleSetBuild.java:283)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:122)</p></pre>
</details>
</details>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `duplicates` from Jira: <a class="jira-relationship" href="https://issue-redirect.jenkins.io/issue/6514">JENKINS-6514</a>]</i>
